config/routes.rb
Rails.application.routes.draw do



  resources :users do
    resources :links
  end

  root 'links#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users  = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end


  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopLinks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert") %>
   <% end %>

   <!-- Navigation -->
   <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container">
           <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>
               <%= link_to 'Top Links', root_url, class: "navbar-brand" %>
           </div>
           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav">
                   <li>
                       <%= link_to 'Add new user', new_user_path %>
                   </li>
                   <li>
                       <a href="#">Links</a>
                   </li>
                   <li>
                       <a href="#">Contact</a>
                   </li>
               </ul>
           </div>
           <!-- /.navbar-collapse -->
       </div>
       <!-- /.container -->
   </nav>

   <!-- Page Content -->
   <div class="container">

       <div class="row">
           <div class="col-lg-12 text-center">
             <%= yield %>
           </div>
       </div>
       <!-- /.row -->

   </div>
   <!-- /.container -->


  </body>
</html>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/index.html.erb
<h1>Links#index</h1>
<p>Find me in app/views/links/index.html.erb</p>

app/views/links/new.html.erb
<h1>Links#new</h1>
<p>Find me in app/views/links/new.html.erb</p>

app/views/links/show.html.erb
<h1>Links#show</h1>
<p>Find me in app/views/links/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@user.errors.count, "error") %> prevented this user from saving</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<p>
  <%=  f.label :first_name %><br/>
  <%=  f.text_field :first_name%><br/>
</p>

<p>
  <%=  f.label :last_name %><br/>
  <%=  f.text_field :last_name%><br/>
</p>

<p>
  <%=  f.label :username %><br/>
  <%=  f.text_field :username%><br/>
</p>

<p>
  <%=  f.label :email %><br/>
  <%=  f.email_field :email%><br/>
</p>

<p>
  <%= f.label :password %><br/>
  <%= f.password_field :password %><br/>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user:</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users:</h1>

<% @users.each do |user| %>

<%= user.first_name %>
<%= user.last_name %>
<%= user.username %>

| <%= link_to 'Edit', edit_user_path(user) %>
| <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure' } %>
| <%= link_to 'Show', user_path(user) %>

<br />

<% end %>

app/views/users/new.html.erb
<div id="wrapper">

  <h1>Add new user</h1>

  <%= render 'form' %>
  
</div>

app/views/users/show.html.erb
<h1>Show users</h1>

<%= @user.first_name %> <br/>
<%= @user.last_name %> <br/>
<%= @user.username %> <br/>
<%= @user.email %><br/>